Add Profile-Set-Up Page
902Youth/CU-Frontend pull request #22
Opened 2024-06-17 06:56 UTC by ruru-dev

2024-06-20 16:48 UTC, PeytenBevill commented on src/components/Home/Home.tsx
> -import Icons from "../../Icons/icons";
Why was all of this deleted?

2024-06-20 16:49 UTC, PeytenBevill commented on src/components/Home/Home.tsx
> -import { ProfileQuickView } from "../ProfileQuickView/ProfileQuickView";
And here, why were these imports deleted?

2024-06-20 16:50 UTC, PeytenBevill requested changes
Please review my comments

2024-06-20 22:23 UTC, ruru-dev commented on src/components/Home/Home.tsx
> -import Icons from "../../Icons/icons";
Line 6: Icons import was unused. We can re-add later if needed.
Lines 8 - 19: The `User` interface was extracted to a separate file so it could be more readily reused by the `ProfileSetup` page (among others). See import on line 5 and new file [here](https://github.com/902Youth/CU-Frontend/pull/22/files#diff-95665711e74785b1f2d9f48939e3ef37b0e766f8a2bd431983a96eb3d2d01141).

2024-06-20 22:23 UTC, ruru-dev commented on src/components/Home/Home.tsx
> -import { ProfileQuickView } from "../ProfileQuickView/ProfileQuickView";
Line 1: `useEffect` import was removed since it was unused. We can re-add later if needed.
Line 2: `ProfileQuickView` was moved below to group with other custom component imports.
Line 4: mockData imports were moved to the to the bottom (line 6)

See below

2024-06-22 22:14 UTC, PeytenBevill approved these changes

2024-06-22 22:14 UTC, merged